---
- name: "install | graylog | create docker-compose directory"
  file:
    path: /opt/docker-compose/graylog
    state: directory
    mode: '0755'

- name: 'install | graylog | copy docker-compose file'
  template:
    src: compose/graylog.yml.j2
    dest: "/opt/docker-compose/graylog/docker-compose.yml"
    owner: root
    group: root
    mode: 0644

- name: 'install | graylog | copy .env file'
  template:
    src: compose/.env.j2
    dest: "/opt/docker-compose/graylog/.env"
    owner: root
    group: root
    mode: 0644

- name: 'install | graylog | generate secret graylog env file'
  command: pwgen -N 1 -s 96
  register: reg_graylog_env_secret

- name: 'install | graylog | define secret password into .env file'
  lineinfile:
    path: /opt/docker-compose/graylog/.env
    regexp: '^GRAYLOG_PASSWORD_SECRET='
    line: GRAYLOG_PASSWORD_SECRET="{{ reg_graylog_env_secret.stdout }}"
  when: reg_graylog_env_secret is defined and reg_graylog_env_secret.changed == True

- name: 'install | graylog | generate root password into graylog env file'
  command: "echo -n {{ GRAYLOG_ROOT_PASSWORD_SHA2_password }} | shasum -a 256 | awk '{print $1}'"
  register: reg_GRAYLOG_ROOT_PASSWORD_SHA2_password

- name: 'install | graylog | define secret password into .env file'
  lineinfile:
    path: /opt/docker-compose/graylog/.env
    regexp: '^GRAYLOG_ROOT_PASSWORD_SHA2='
    line: GRAYLOG_ROOT_PASSWORD_SHA2="{{ reg_GRAYLOG_ROOT_PASSWORD_SHA2_password.stdout }}"
  when: reg_GRAYLOG_ROOT_PASSWORD_SHA2_password is defined and reg_GRAYLOG_ROOT_PASSWORD_SHA2_password.changed == True

- name: 'install | graylog | install unit file'
  template:
    src: systemd/docker-compose.service.j2
    dest: "/etc/systemd/system/docker-compose@graylog.service"
    owner: root
    group: root
    mode: 0600
  notify:
    - 'docker-graylog-restart'

- name: 'install | graylog | enable service'
  systemd:
    daemon_reload: yes
    name: "docker-compose@graylog"
    enabled: true
  ignore_errors: '{{ ansible_check_mode }}'
