---
- name: 'include asserts'
  include_tasks: 'asserts.yml'

- name: 'requirements'
  include_tasks: 'requirements.yml'

## graylog server install
- name: 'server install'
  include_tasks: "install.yml"

## geoip install
- name: 'geoip install'
  include_tasks: "geoip_install.yml"
  tags: [ 'geoip' ]
