---
- name: 'requirement | update APT Cache'
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: 'requirement | pre-requirements install'
  apt:
    name:
      - curl
      - jq
      - pwgen
    state: present

- name: 'requirement | docker-compose | check if docker and docker-compose are installed'
  shell:
    cmd: "{{ item }} --help"
  register: result
  check_mode: false
  changed_when: false
  failed_when: result.rc != 0 and result.rc != 127
  with_items:
    - docker
    - docker-compose
